name: Workflow

on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Initialization
         continue-on-error: false
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://SamXD7:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials


       - name: Cloning Repo
         continue-on-error: false
         run: |
           git clone -b main https://SamXD7:${{ secrets.GH_TOKEN }}@github.com/SamXD7/Encoder.git
       - name: Running Bot
         timeout-minutes: 240
         continue-on-error: false
         run: |
           cd Encoder
           docker build -t encode2tg . && docker run encode2tg

       - name: Loop Workflow
         continue-on-error: false
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
